### PR TITLE
Adding additional tagging

### LINKED ISSUE #11: Tag images dev and stable
It would be nice to have multiple tags for tracking dev and stable for CI systems.

http://stackoverflow.com/questions/21928780/create-multiple-tag-docker-image

Has an example on how to tag the same image multiple times.

Might also be nice to have a google/dart:1.12 similar to what nodejs does for images.

### PR DESCRIPTION
**Pull request by donny-dont**
This pull requests adds additional tags which is more inline with node and other library packages.

For stable the following tags are pushed
```
google/dart:latest
google/dart:major.minor.patch
google/dart:major.minor
google/dart:major
```
For dev the following tags are pushed
```
google/dart:dev
google/dart:major.minor.patch
google/dart:major.minor
```

A `docker images` command results in this when 1.13.0-dev.7.3 and 1.12.1 are run through the modified script

```
REPOSITORY                                                    TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
test/dart-runtime                                             latest              aa5d51fc6617        2 minutes ago       215.4 MB
test/dart-runtime                                             1                   aa5d51fc6617        2 minutes ago       215.4 MB
test/dart-runtime                                             1.12                aa5d51fc6617        2 minutes ago       215.4 MB
test/dart-runtime                                             1.12.1              aa5d51fc6617        2 minutes ago       215.4 MB
test/dart-runtime-base                                        latest              c01d9e8bef47        2 minutes ago       215.4 MB
test/dart-runtime-base                                        1                   c01d9e8bef47        2 minutes ago       215.4 MB
test/dart-runtime-base                                        1.12                c01d9e8bef47        2 minutes ago       215.4 MB
test/dart-runtime-base                                        1.12.1              c01d9e8bef47        2 minutes ago       215.4 MB
test/dart                                                     latest              3d199bda74a0        3 minutes ago       215.4 MB
test/dart                                                     1                   3d199bda74a0        3 minutes ago       215.4 MB
test/dart                                                     1.12                3d199bda74a0        3 minutes ago       215.4 MB
test/dart                                                     1.12.1              3d199bda74a0        3 minutes ago       215.4 MB
test/dart-runtime                                             dev                 a8fa0a909ff9        6 minutes ago       211.8 MB
test/dart-runtime                                             1.13                a8fa0a909ff9        6 minutes ago       211.8 MB
test/dart-runtime                                             1.13.0-dev.7.3      a8fa0a909ff9        6 minutes ago       211.8 MB
test/dart-runtime-base                                        1.13                48973b8f240d        7 minutes ago       211.8 MB
test/dart-runtime-base                                        1.13.0-dev.7.3      48973b8f240d        7 minutes ago       211.8 MB
test/dart-runtime-base                                        dev                 48973b8f240d        7 minutes ago       211.8 MB
test/dart                                                     1.13                09909191007e        7 minutes ago       211.8 MB
test/dart                                                     1.13.0-dev.7.3      09909191007e        7 minutes ago       211.8 MB
test/dart                                                     dev                 09909191007e        7 minutes ago       211.8 MB
```

Please double check that the push works properly for google. I didn't have a registry I could push to.

Fixes #11

### CODE REVIEW

**Comment by donny-dont** [comment]
Also if the tagging scheme is acceptable I'll open the README.md for it in another pull request.

**Comment by whesse** [comment]
I don't think we should tag a dev version with 1.13.  All dev versions should have "dev" in them, and regular version numbers should be reserved for stable release versions.

I'm also a bit uncertain about the "1" tag - it seems to me like people should not implicitly jump from one minor version to the next, without knowing about the changes.  But if that is really the standard, I am OK with it.  All the other tags are OK with me, but we should decide on this.  @sethladd @kevmoo @sgjesse @ricowind

**Comment by sgjesse** [comment]
I agree with Bill, for stable:

```
google/dart:latest
google/dart:major.minor.patch
google/dart:major.minor
```

and for dev:

```
google/dart:dev
google/dart:major.minor.patch-dev
google/dart:major.minor-dev
```

**Comment by donny-dont** [comment]
With regards to the `google/dart:1` tag this seems to be the convention in the official library stacks. With Python it's obviously needed, https://hub.docker.com/_/python/, but even Golang has a 1 tag, https://hub.docker.com/_/golang/. On the plus side the script will almost be ready for a Dart 2.0. It probably needs some logic around when to push the latest tag in that case.

For the dev tags I went with pushing major:minor as well because it seemed more user friendly to people downstream. As an example if my app required less restrictive mixins I could target `FROM google/dart:1.13` in my Dockerfile, and then when 1.13 gets promoted to stable I can rebuild my Dockerfile and get the latest stable without any changes.

I don't really see any precedence for dev SDKs in the language stacks but I liked the behavior that I could target a dev major.minor and eventually that tag gets overwritten when stable comes around.

**Comment by donny-dont** [comment]
Any additional thoughts here? Anything wrong with the script or is that part good to go?

**Comment by donny-dont** [comment]
@mit-mit is this something you can review? @kwalrath suggested you.

**Comment by kevmoo** [comment]
I'd love @sgjesse and @whesse to chime in again, if they wouldn't mind

**Comment by sgjesse** [comment]
I am OK with the 1 tag for 1.x.y stable (until Dart 2 it will work like latest). However for dev versions I still think 'dev' should be part of the name. I don't like version numbers without 'dev' in them to refer to developer versions. When looking at a version number like 1.13 it should be certain to refer to a stable version.

**Comment by donny-dont** [comment]
Okay if @whesse wants the -dev for the tagging in there as well that's fine I'll modify accordingly. I can see the argument that you don't want it to seem as though its a released version. I was coming at it as more of a CI or bleeding edge dev thing so less tags would be nice. That and I can't see anyone really wanting the dev after the stable has been released.

Are the script modifications okay by you guys? We're in fairly different timezones so I'll hopefully have time to make whatever changes are requested tomorrow.

**Comment by mit-mit** [comment]
I agree that we need dev in the tags for that channel. And I also don't understand the use of the x tags -- when would someone use that as opposed to latest?

Finally, I think it would be more consistent to format the dev tags like this:

```
google/dart:latest-dev
google/dart:major.minor.patch-dev
google/dart:major.minor-dev
```

**Comment by sgjesse** [comment]
@whesse Bill, can you take another look?

**Comment by kwalrath** [comment]
Pinging @whesse...

**Comment by whesse** [comment]
LGTM.

**Comment by whesse** [comment]
After merging this change, the script build_push.sh fails just before pushing.
If you have a fix for this, please upload it, otherwise, we can revert.

The output is:
 ....
rigger 1, RUN pub get
Step 0 : RUN pub get
 ---> Running in 34d8f3b8b3bb
Resolving dependencies...
Downloading http_server 0.9.5+1...
Downloading mime 0.9.3...
Downloading path 1.3.9...
Got dependencies!
Trigger 2, ADD . /app/
Step 0 : ADD . /app/
Trigger 3, RUN pub get --offline
Step 0 : RUN pub get --offline
 ---> Running in a78d4cc116e7
Resolving dependencies...
Got dependencies!
 ---> d0ccc1200a9a
Removing intermediate container 34d8f3b8b3bb
Removing intermediate container 869a41b10cd1
Removing intermediate container a78d4cc116e7
Removing intermediate container 0609c5f6c643
Successfully built d0ccc1200a9a
Validated 1.14.0-dev.7.0 in google/dart-hello
Validated 1.14.0-dev.7.0 in google/dart-hello:1.14.0-dev.7.0
Pushing...
./build_push.sh: line 131: get_images: command not found

**Comment by donny-dont** [comment]
I ran `build_push.sh` locally and it gets past that issue if you change `get_images` to `get_tag`. Its getting to the push part as I see. 

```
unauthorized: access to the requested resource is not authorized
```

I'll push to a private registry and see if things work there but if you want to locally make the change feel free. @whesse

**Pull request merged**
